[project]
name = "sbx1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "open3d",
    "pyside6>=6.11.1",
    "pyvista>=0.48.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
